# This image is intended to be a complete build 
# with mysql,postgres and sqlite drivers
FROM oven/bun:latest AS bun

FROM php:8.4-fpm

# Install dependencies
RUN set -eux; \
    apt-get update; \
    apt-get upgrade -y; \
    apt-get install -y --no-install-recommends \
        git \
        curl \
        libfcgi0ldbl \
        libfcgi-bin \
        libsodium-dev \
        libmemcached-dev \
        libcurl4-gnutls-dev \
        libz-dev \
        libpq-dev \
        libjpeg-dev \
        libpng-dev \
        libfreetype6-dev \
        libssl-dev \
        libwebp-dev \
        libxpm-dev \
        libmcrypt-dev \
        libonig-dev \
        libxml2-dev \
        libsqlite3-dev \
        sqlite3 \
        libzip-dev \
        zip \
        unzip \
        default-mysql-client \
        postgresql-client; \
    apt-get autoclean; \
    apt-get autoremove -y; \
    rm -rf /var/lib/apt/lists/*

# INSTALL PHP MODULES
RUN set -eux; \  
    docker-php-ext-install \
        pdo_mysql \
        pdo_pgsql \
        pdo_sqlite \
        mbstring \
        exif \
        pcntl \
        bcmath \
        zip \
        xml \
        pgsql \
        sodium \
        intl \
        curl; \
    docker-php-ext-configure \
        gd \
        --prefix=/usr \
        --with-jpeg \
        --with-webp \
        --with-xpm \
        --with-freetype; \
    docker-php-ext-install gd; 

RUN usermod -u 1000 www-data

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
# CopY BUN
COPY --from=bun /usr/local/bin/bun /usr/local/bin

RUN chmod 755 -R /var/www

WORKDIR /var/www

CMD ["php-fpm"]

